### ISSUE TITLE
ZMPT101B AC Voltage Sensor

### ISSUE THREAD

**Issue by RahulGoyal-tech** [Embedded-Squad/Energy-Meter#7]
Integrate ZMPT101B Single phase AC Voltage sensor to esp32 board. Function should also take in pin number to which sensor is connected.

**Comment by RahulGoyal-tech** [comment]
Approximate Deadline: 13-02-2022

**Comment by Dharmendra7798** [comment]
Can I get the calculation of ZMPT101B module

**Comment by RahulGoyal-tech** [comment]
> Can I get the calculation of ZMPT101B module

https://github.com/Embedded-Squad/Energy-Meter/blob/develop/Firmware/energy-meter/src/zmpt.cpp
You can check the above code. It is a simple linear conversion of minimum and maximum ADC values to minimum and maximum Voltage obtained.

**Comment by Dharmendra7798** [comment]
> > Can I get the calculation of ZMPT101B module
> 
> https://github.com/Embedded-Squad/Energy-Meter/blob/develop/Firmware/energy-meter/src/zmpt.cpp You can check the above code. It is a simple linear conversion of minimum and maximum ADC values to minimum and maximum Voltage obtained.

I want calculation of circuit of this module.

**Comment by RahulGoyal-tech** [comment]
> > > Can I get the calculation of ZMPT101B module
> > 
> > https://github.com/Embedded-Squad/Energy-Meter/blob/develop/Firmware/energy-meter/src/zmpt.cpp You can check the above code. It is a simple linear conversion of minimum and maximum ADC values to minimum and maximum Voltage obtained.
> 
> I want calculation of circuit of this module.
> 

I have not worked with the calculations of module itself yet.

**Comment by Dharmendra7798** [comment]
> 

ok
